#!/usr/bin/env python3
"""Regenerate the 1,400 exact integer cases using Python as an independent oracle.

The checked-in .inc is consumed by GoogleTest; running tests needs no Python.
"""
import json
from pathlib import Path
import random

random_source = random.Random(25092026)
cases = []


def add(expression, result):
    if isinstance(result, bool):
        result = "صحيح" if result else "خطا"
    cases.append((expression, str(result)))


for _ in range(100):
    a = random_source.getrandbits(random_source.choice([47, 48, 63, 64, 65, 128, 256, 512])) * (-1 if random_source.randrange(2) else 1)
    b = random_source.getrandbits(random_source.choice([47, 48, 63, 64, 65, 128, 256])) * (-1 if random_source.randrange(2) else 1) or 1
    for operator, result in [("+", a+b), ("-", a-b), ("*", a*b), ("&", a&b), ("|", a|b), ("^", a^b), ("=", a == b), ("<", a < b), (">", a > b)]:
        add(f"({a}) {operator} ({b})", result)
    # Fairuz remainder truncates toward zero, unlike Python's signed %.
    quotient = abs(a) // abs(b) * (-1 if (a < 0) != (b < 0) else 1)
    add(f"({a}) % ({b})", a - quotient*b)
    add(f"({a*b}) / ({b})", a)
    count = random_source.choice([0, 31, 32, 47, 48, 63, 64, 65, 127, 256, 513])
    add(f"({a}) << {count}", a << count)
    add(f"({a}) >> {count}", a >> count)
    add(f"~({a})", ~a)

assert len(cases) == 1400
output = Path(__file__).parent / "test_cases" / "integer_oracle.inc"
with output.open("w") as stream:
    stream.write("// Generated by tests/generate_integer_oracle.py; Python seed 25092026.\n")
    stream.write("// Exact expected values are independent of the Fairuz implementation.\n")
    for expression, expected in cases:
        stream.write("{" + json.dumps(expression, ensure_ascii=False) + ", " + json.dumps(expected, ensure_ascii=False) + "},\n")
