// motherfucker dah put any file you create here to get any compile time errors
// in case you do not want to write test cases because you want to go masturbate

#include "../include/diag/diagnostic.hpp"
#include "../include/diag/diagnostic_codes.hpp"
#include "../include/diag/diagnostic_emitter.hpp"
#include "../include/diag/diagnostic_engine.hpp"
#include "../include/diag/diagnostic_label.hpp"
#include "../include/diag/fixit.hpp"
#include "../include/diag/severity.hpp"
#include "../include/input/buffer/base.hpp"
#include "../include/input/buffer/input_buffer.hpp"
/// @todo:remove
#include "../include/input/file_manager.hpp"
#include "../include/input/source_manager.hpp"
#include "../include/lex/lexer.hpp"
#include "../include/lex/sym_table/entry.hpp"
#include "../include/lex/sym_table/table.hpp"
#include "../include/lex/token.hpp"
#include "../include/lex/util.hpp"
#include "../include/macros.hpp"
#include "../include/parser/ast/ast.hpp"
#include "../include/parser/ast/printer.hpp"
#include "../include/parser/optim.hpp"
#include "../include/parser/analyzer.hpp"
#include "../include/parser/cfg.hpp"
#include "../include/parser/codegen.hpp"
#include "../include/parser/incremental.hpp"
#include "../include/parser/language_server.hpp"
#include "../include/parser/parallel.hpp"
#include "../include/parser/profiler.hpp"
#include "../include/runtime/allocator/arena.hpp"
#include "../include/runtime/object/object.hpp"
#include "../include/runtime/vm/bytecode.hpp"
#include "../include/runtime/vm/btcompiler.hpp"
#include "../include/runtime/vm/gc.hpp"
#include "../include/runtime/vm/jit.hpp"
#include "../include/runtime/vm/vm.hpp"